# Generated by Django 4.2 on 2023-04-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.TextField(max_length=400)),
                ('brief_description', models.TextField(max_length=500)),
                ('video_genre', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=150)),
                ('video_link', models.TextField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
